// ============================================================
// CloudFront Function — viewer-request URI rewriter
// ------------------------------------------------------------
// This file is the SOURCE OF TRUTH for the function; the live
// function in the CloudFront console must be updated manually
// whenever this changes. See `infra/cloudfront/README.md` for
// the exact publish steps.
//
// Responsibilities:
//   1. Route per-subdomain traffic into S3 key prefixes.
//      e.g. site.dev.aiseo.tips/foo → /site/foo
//      e.g. acme.dev.aiseo.tips/foo → /acme/foo
//   2. For the `site` subdomain, serve prerendered HTML
//      snapshots for a small allow-list of routes so
//      social-media crawlers (Kakao, Facebook, X, Naver)
//      receive per-page OG/meta tags. Human visitors still
//      get the React SPA mounted after the HTML arrives —
//      the body is identical to index.html.
//   3. Everything else on the `site` subdomain falls back to
//      /site/index.html (SPA shell).
//
// IMPORTANT — CloudFront Function runtime restrictions:
//   - ES5-only. No const/let, no arrow fns, no spread, no
//     Array.includes, no String.startsWith, no template
//     literals. Use var + String.indexOf + endsWith patterns.
//   - No `require`, no Node stdlib, no network.
//   - Max execution time ~1ms. Keep everything O(routes).
//   - Single file, single handler named `handler`.
// ============================================================

function handler(event) {
  var request = event.request;
  var host = request.headers.host.value;

  // Base domains — longest first so dev.aiseo.tips matches
  // before aiseo.tips (otherwise `host.endsWith('.aiseo.tips')`
  // would greedily capture 'dev' as the siteId).
  var baseDomains = ['dev.aiseo.tips', 'aiseo.tips'];
  var siteId = '';

  for (var i = 0; i < baseDomains.length; i++) {
    if (host === baseDomains[i]) {
      siteId = '';
      break;
    }
    var suffix = '.' + baseDomains[i];
    if (host.endsWith(suffix)) {
      siteId = host.substring(0, host.length - suffix.length);
      break;
    }
  }

  if (siteId) {
    var uri = request.uri;

    // ── site subdomain (SPA + prerendered OG snapshots) ──
    if (siteId === 'site') {
      // Static assets (anything with a file extension) — pass
      // through as-is under the /site/ prefix. Must come first
      // so `/assets/index-abc123.js` doesn't fall through to
      // the SPA fallback.
      if (uri.match(/\.\w+$/)) {
        request.uri = '/' + siteId + uri;
        return request;
      }

      // Strip any trailing slash for route matching so
      // /course2026 and /course2026/ both hit the same entry.
      var routeKey = uri;
      if (routeKey.length > 1 && routeKey.charAt(routeKey.length - 1) === '/') {
        routeKey = routeKey.substring(0, routeKey.length - 1);
      }

      // Prerendered fixed routes. Each entry maps a public
      // path to an S3 key that was generated by
      // `frontend/scripts/prerender.mjs` at build time. Add
      // new entries here AND in that script when introducing
      // a new marketing sub-page.
      var PRERENDERED_FIXED = {
        '/course2026': '/site/course2026/index.html',
        '/support2026': '/site/support2026/index.html',
        '/events2026': '/site/events2026/index.html',
        '/events2026/free': '/site/events2026/free/index.html',
        '/events2026/paid': '/site/events2026/paid/index.html',
        '/blog': '/site/blog/index.html',
      };

      if (PRERENDERED_FIXED[routeKey]) {
        request.uri = PRERENDERED_FIXED[routeKey];
        return request;
      }

      // Prerendered blog posts — `/blog/<slug>` resolves to
      // `/site/blog/<slug>/index.html`, which the blog Lambda
      // writes on post save. Slug allow-list: lowercase
      // letters, digits, and hyphens (matches the backend
      // SLUG_RE). If the slug doesn't match or the S3 object
      // is missing, S3 will 404 and CloudFront's custom error
      // response falls back to /site/index.html (SPA shell),
      // so the post still renders client-side.
      var blogMatch = routeKey.match(/^\/blog\/([a-z0-9-]+)$/);
      if (blogMatch) {
        request.uri = '/site/blog/' + blogMatch[1] + '/index.html';
        return request;
      }

      // Default SPA fallback — everything else (unknown
      // routes, /admin/*, /?auth=login, …) gets the shell.
      request.uri = '/site/index.html';
      return request;
    }

    // ── Per-user sites (acme.dev.aiseo.tips) ──
    if (uri === '/' || uri === '') {
      request.uri = '/' + siteId + '/index.html';
    } else if (uri.endsWith('/')) {
      request.uri = '/' + siteId + uri + 'index.html';
    } else {
      request.uri = '/' + siteId + uri;
    }
  } else {
    // ── apex (aiseo.tips / dev.aiseo.tips) clean URL rewrites ──
    // S3 는 sub-directory 의 implicit index 를 제공하지 않으므로
    // `/library` 같은 확장자 없는 깔끔한 경로는 여기서 명시적으로
    // index.html 로 리라이트. 신규 페이지 추가 시 같은 패턴으로
    // 이 블록에 한 줄씩 추가.
    var apexUri = request.uri;
    if (apexUri === '/library' || apexUri === '/library/') {
      request.uri = '/library/index.html';
    }
  }

  return request;
}
